//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroppedImagePlugin.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CroppedImagePlugin.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert crop control colors.
        /// </summary>
        public static string Invertcropcontrolcolors {
            get {
                return ResourceManager.GetString("Invertcropcontrolcolors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode (crop/scale).
        /// </summary>
        public static string modeCrapScale {
            get {
                return ResourceManager.GetString("modeCrapScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from files.
        /// </summary>
        public static string pickFromFiles {
            get {
                return ResourceManager.GetString("pickFromFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh cropping.
        /// </summary>
        public static string Refreshcropping {
            get {
                return ResourceManager.GetString("Refreshcropping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you modified values manually and want to ui to sync up.
        /// </summary>
        public static string RefreshcroppingTooltip {
            get {
                return ResourceManager.GetString("RefreshcroppingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X offset.
        /// </summary>
        public static string Xoffset {
            get {
                return ResourceManager.GetString("Xoffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y offset.
        /// </summary>
        public static string Yoffset {
            get {
                return ResourceManager.GetString("Yoffset", resourceCulture);
            }
        }
    }
}
